apiVersion: v1
kind: Namespace
metadata:
  name: build-windows-dockerfile
---
apiVersion: batch/v1
kind: Job
metadata:
  name: build-windows-dockerfile
  namespace: build-windows-dockerfile
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: build-windows-dockerfile
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - windows
      containers:
      - name: build
        image: estafette/golang:1.15.6-windowsservercore-ltsc2019
        env:
        - name: GIT_REPOSITORY
          value: "${GIT_REPOSITORY}"
        - name: ESTAFETTE_GIT_NAME
          value: "${ESTAFETTE_GIT_NAME}"
        - name: DOCKERFILE
          value: "${DOCKERFILE}"
        - name: DOCKER_IMAGE
          value: "${DOCKER_IMAGE}"
        - name: DOCKER_USERNAME
          value: "${DOCKER_USERNAME}"
        - name: DOCKER_PASSWORD
          value: "${DOCKER_PASSWORD}"
        - name: CGO_ENABLED
          value: "0"
        - name: GOOS
          value: "windows"
        - name: GOARCH
          value: "amd64"
        command:
        - powershell.exe
        - -command
        - >-
          Write-Host 'Updating PATH for docker...';
          $env:PATH = 'C:\Program Files\Docker;' + $env:PATH;
          [Environment]::SetEnvironmentVariable('PATH', $env:PATH, [EnvironmentVariableTarget]::Machine);

          Write-Host ('Cloning {0} to C:/work ...' -f $env:GIT_REPOSITORY);
          git clone $env:GIT_REPOSITORY C:/work;
          cd C:/work;

          go build -v  -o ./$env:ESTAFETTE_GIT_NAME.exe;
          dir;

          Write-Host ('Building docker image {0} from file {1} ...' -f $env:DOCKER_IMAGE, $env:DOCKERFILE);
          docker build -t $env:DOCKER_IMAGE -f $env:DOCKERFILE .;

          Write-Host 'Logging in to docker hub...';
          docker login -u $env:DOCKER_USERNAME -p $env:DOCKER_PASSWORD;

          Write-Host ('Pushing docker image {0} to docker hub ...' -f $env:DOCKER_IMAGE);
          docker push $env:DOCKER_IMAGE;

        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "6"
            memory: "21474836480"
          requests:
            cpu: "6"
            memory: "21474836480"
        volumeMounts:
        - name: docker-socket
          mountPath: \\.\pipe\docker_engine
        - name: docker-cli
          mountPath: C:/Program Files/Docker
      restartPolicy: Never
      tolerations:
      - effect: NoSchedule
        key: role
        operator: Equal
        value: privileged
      - effect: NoSchedule
        key: node.kubernetes.io/os
        operator: Equal
        value: windows
      volumes:
      - name: docker-socket
        hostPath:
          path: \\.\pipe\docker_engine
      - name: docker-cli
        hostPath:
          path: C:/Program Files/Docker